### ISSUE TITLE
self-hosting available

### ISSUE THREAD

**Issue by nagim** [matthew-james/gitbook-plugin-asciinema#1]
Hi,

This is an awesome plugin!
Does it support the self-hosted version as well (when you're not hosting it on [asciinema.org](http://asciinema.org) but among your own website assets)?

Thanks!

**Comment by matt-allan** [comment]
Hi,

It won't really work for self hosted.

This plugin requires a URL for the screencast and a png image to render in book view, in addition to the javascript player for the web view.

If you are self hosting [like this](https://github.com/asciinema/asciinema-player#use-the-player-in-your-html-page) those assets don't exist.

For this plugin to work the assets would have to be organized exactly the same as they are on asciinema, i.e:

```
Image: {url}{cast_id}.png
page: {url}{cast_id}
JS: {url}{cast_id}.js
```

**Comment by nagim** [comment]
Hi,

Thanks for the reply, this is a good pointer.
I might go ahead and create a separate plugin for self-hosting version.

Cheers,
Imre
